<?php

/**
 * @file
 * A module showing list of commonly used hook in Drupal Development.
 * 
 * This module provides a block that lists all of the commonly used hook 
 * in Drupal Development.
 */

/**
 * Implements hook_help().
 */
function hooklist_help($path, $arg) {
  if ($path == 'admin/help#hooklist') {
    return t('Lists commonly used hooks in Drupal Development.');
  }
}

/**
 * Implements hook_block_info().
 */
function hooklist_block_info() {
  $blocks = array();
    
  $blocks['list_hooks'] = array(
    'info' => t('A listing of all of the commonly used hooks in Drupal Development.'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hooklist_block_view($block_name = '') {
  module_load_include('inc', 'hooklist', 'hooklist');
  
  $hooklist_items = get_hooklist_items();
  
  // Create an empty block
  $block = array(
    'subject' => '',
    'content' => '',
  );
  
  switch ($block_name) {
    case 'list_hooks':
      // Set the block title.
      $block['subject'] = t('List of commonly used hooks');
      
      // Theme the list of tags for selection.
      $block['content']['tag-filter'] = get_renderable_tags_array(array(
        'required', 'optional', 'info', 'debug'
      ), TRUE);
      
      // Theme the list of hooks.
      $block['content']['list'] = array(
        '#theme' => 'item_list__hooklist',
        '#items' => $hooklist_items,
        '#pre_render' => array('hooklist_item_list_child_render'),
      );
      
      // Add highlight CSS file to style the code.
      $block['content']['#attached']['css'][] = 
        drupal_get_path('module', 'hooklist') . '/highlight.default.css';
      
      // Add a CSS file to style the block.
      $block['content']['#attached']['css'][] = 
        drupal_get_path('module', 'hooklist') . '/hooklist.css';
      
      // Add highlight.js for syntax highlighting
      $block['content']['#attached']['js'][] = 
        drupal_get_path('module', 'hooklist') . '/highlight.pack.js';
      
      // Add a JS file to handle client side script.
      $block['content']['#attached']['js'][] = 
        drupal_get_path('module', 'hooklist') . '/hooklist.js';
  }
  
  return $block;
}

/**
 * Render the child elements of theme_item_list() before its data is themed.
 */
function hooklist_item_list_child_render($elements) {
  foreach (array_keys($elements['#items']) AS $key) {
    
    // Take the renderable array that we set in hooklist_block_view() and
    // render it into the string that theme_item_list() expects.
    if (is_array($elements['#items'][$key]['data'])) {
      $elements['#items'][$key]['data'] = drupal_render($elements['#items'][$key]['data']);
    }
  }
  return $elements;
}

/**
 * Implements hook_theme().
 */
function hooklist_theme($existing, $type, $theme, $path) {
  $themes = array(
    'hooklist_block_item' => array(
      'variables' => array(
        'hook_name' => '',
        'url' => '',
        'description' => '',
        'tips_array' => '',
        'category' => '',
        'tags_array' => array(),
        'sample_code' => '',
      ),
      'template' => 'hooklist-block-item',
    ),
    'hooklist_tags' => array(
      'render element' => 'element',      
    ),
  );
  
  return $themes;
}

/**
 * Preprocesses hooklist block item variables
 */
function template_preprocess_hooklist_block_item(&$variables) {
  
  // Create a renderable array for the link
  $variables['link'] = array(
    '#type' => 'link',
    '#title' => $variables['hook_name'],
    '#href' => $variables['url'],
    '#options' => array(
      'attributes' => array(
        'target' => '_blank',
      ),
    ),
  );
  
  // Set renderable array for the tips
  $variables['tips'] = array(
    '#theme' => 'item_list',
    '#items' => $variables['tips_array'],
  );
          
  // Set renderable array for the tags
  $variables['tags'] = get_renderable_tags_array($variables['tags_array']);
}

/**
 * Return a renderable array from the given tags array
 * 
 * @param array $tags_array an array of tag type (string)
 * @param boolean $is_filter append the class 'filter' if TRUE
 */
function get_renderable_tags_array($tags_array, $is_filter = FALSE) {
  $items = array();
  
  foreach ($tags_array as $tag) {
    $item = array(
      'data' => $tag,
      'class' => array(
        'tag', 
        'tag-' . str_replace(' ', '-', strtolower($tag)),
        'selected',
      ),
    );
    
    if ($is_filter) {
      $item['class'][] = 'filter';
    }
    
    $items[] = $item;
  }
  
  return array(
    '#theme' => 'item_list', 
    '#items' => $items,
  ); 
}