<?php

/**
 * @file
 * A module showing list of commonly used hook in Drupal Development.
 * 
 * This module provides a block that lists all of the commonly used hook 
 * in Drupal Development.
 */

/**
 * Implements hook_help().
 */
function hooklist_help($path, $arg) {
  if ($path == 'admin/help#hooklist') {
    return t('Lists commonly used hooks in Drupal Development.');
  }
}

/**
 * Implements hook_block_info().
 */
function hooklist_block_info() {
  $blocks = array();
    
  $blocks['list_hooks'] = array(
    'info' => t('A listing of all of the commonly used hooks in Drupal Development.'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hooklist_block_view($block_name = '') {
  $items = get_hooklist_items();
  
  // Create an empty block
  $block = array(
    'subject' => '',
    'content' => '',
  );
  
  switch ($block_name) {
    case 'list_hooks':
      // Set the block title.
      $block['subject'] = t('List of commonly used hooks');
      
      // Theme the list of hooks.
      $block['content']['list'] = array(
        '#theme' => 'item_list__hooklist',
        '#items' => $items,
        '#pre_render' => array('hooklist_item_list_child_render'),
      );
      
      // Add a CSS file to style the block.
      $block['content']['#attached']['css'][] = 
        drupal_get_path('module', 'hooklist') . '/hooklist.css';
      
      // Add a JS file to toggle sample code.
      $block['content']['#attached']['js'][] = 
        drupal_get_path('module', 'hooklist') . '/hooklist.js';
  }
  
  return $block;
}

/**
 * Render the child elements of theme_item_list() before its data is themed.
 */
function hooklist_item_list_child_render($elements) {
  foreach (array_keys($elements['#items']) AS $key) {
    // Take the renderable array that we set in hooklist_block_view() and
    // render it into the string that theme_item_list() expects.
    if (is_array($elements['#items'][$key]['data'])) {
      $elements['#items'][$key]['data'] = drupal_render($elements['#items'][$key]['data']);
    }
  }
  return $elements;
}

/**
 * Implements hook_theme().
 */
function hooklist_theme($existing, $type, $theme, $path) {
  return array(
    'hooklist_block_item' => array(
      'variables' => array(
        'hook_name' => '',
        'url' => '',
        'description' => '',
        'category' => '',
        'tags_array' => array(),
        'sample_code' => '',
      ),
      'template' => 'hooklist-block-item',
    ),
  );
}

/**
 * Preprocesses hooklist block item variables
 */
function template_preprocess_hooklist_block_item(&$variables) {
  
  // Create a renderable array for the link
  $variables['link'] = array(
    '#type' => 'link',
    '#title' => $variables['hook_name'],
    '#href' => $variables['url'],
    '#options' => array(
      'attributes' => array(
        'target' => '_blank',
      ),
    ),
  );
  
  // Create a renderable array for the tags
  $variables['tags'] = array(
    '#theme' => 'item_list',
    '#items' => $variables['tags_array'],    
  );
}

function get_hooklist_items() {
  $items = array();
  
  $items[] = array(
    'data' => array(
      '#theme' => 'hooklist_block_item',
      '#hook_name' => 'hook_help()',
      '#url' => 'https://api.drupal.org/api/drupal/modules/system/system.api.php/function/hook_help/7',
      '#description' => 'Provides online user help.',
      '#category' => 'System',
      '#tags_array' => array('data' => array()),
      '#sample_code' => check_plain(
        "function first_help(\$path, \$arg) { \n" .
        "  if (\$path == 'admin/help#first') { \n" . 
        "    return t('A demonstration module.'); \n" .
        "  } \n" .
        "}"
      ),
    ),
    'class' => array('hook'),
  );
  
  $items[] = array(
    'data' => array(
      '#theme' => 'hooklist_block_item',
      '#hook_name' => 'hook_block_info()',
      '#url' => 'https://api.drupal.org/api/drupal/modules/block/block.api.php/function/hook_block_info/7',
      '#description' => 'Define all blocks provided by the module.',
      '#category' => 'Block',
      '#tags_array' => array('data' => array('required')),
      '#sample_code' => check_plain(
        "function first_block_info() { \n" .
        "  \$blocks = array(); \n\n" .
        "  \$blocks['list_modules'] = array( \n" .
        "    'info' => t('A listing of all of the enabled modules.'), \n" .
        "    'cache' => DRUPAL_NO_CACHE, \n" .
        "  ); \n\n" .
        "  return \$blocks; \n" .
        "}"
      ),
    ),
    'class' => array('hook'),
  );
  
  $items[] = array(
    'data' => array(
      '#theme' => 'hooklist_block_item',
      '#hook_name' => 'hook_block_view()',
      '#url' => 'https://api.drupal.org/api/drupal/modules/block/block.api.php/function/hook_block_view/7',
      '#description' => 'Return a rendered or renderable view of a block.',
      '#category' => 'Block',
      '#tags_array' => array('data' => array('required')),
      '#sample_code' => check_plain(
        "function first_block_view(\$block_name = '') { \n" .
        "  if (\$block_name == 'list_modules') { \n" .
        "    \$list = module_list(); \n\n" .
        "    \$theme_args = array('items' => \$list, 'type' => 'ol'); \n" .
        "    \$content = theme('item_list', \$theme_args); \n\n" .
        "    \$block = array( \n" .
        "      'subject' => t('Enabled Modules'), \n" .
        "      'content\' => \$content, \n" .
        "    ); \n\n" .
        "    return \$block; \n" .
        "  } \n" .
        "}"
       ),
     ),
    'class' => array('hook'),
  );
  
  return $items;
}